# For Future (not in current scope)

# org:
#   COMMON_PAT:
#     value: ssm:/org/github/common-pat
#     visibility: all         # all | private | selected
#     # when visibility: selected, specify repos to grant:
#     # selected_repos: [insizon-dev]

# repos:
#   insizon-dev:
#     SAMPLE_TOKEN: literal:abc123

# envs:
#   insizon-dev:
#     dev:
#       DB_PASSWORD: ssm:/app/dev/db_password

# deploy_keys:
#   insizon-dev:
#     - title: "CI read-only"
#       key: file:private/access_key/ci_key.pem.pub
#       read_only: true

# org_webhooks:
#   - name: "events-to-insizon"
#     url: "https://api.insizon.com/github/webhook"
#     content_type: json
#     secret: ssm:-org-webhook-secret
#     active: true
    # events: [push, pull_request, repository, membership]

# gpg_keys:
#   - armored_key: file:private/gpg/ci_key.asc
